# API Keys
api_keys:
  groq: "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"
  google_maps: "AIzaSyALQx3yjmK6P08_xf7pO0yg7cy31dn-IXM"
  yelp: "Tpf8pXDgUeNbvxNIXmA3keOCfu2hs-MSmgGcGo58ej2tnRC0qoaAVYujVI0p50iDy5c2oxMYi6NHcq_6K3VOVrtzT1aTGJS_IJZxvt_idCiVQKlWRsLGpU2r1OHdZ3Yx"

# Model Configuration
models:
  llm:
    name: "llama-3.3-70b-versatile"  # Groq's Llama 3.3 70B Versatile model
    temperature: 0.7
    max_tokens: 2000
  embedding:
    name: "all-MiniLM-L6-v2"
    dimension: 384

# Application Settings
app:
  debug: false
  host: "0.0.0.0"
  port: 8501

# Data Paths
paths:
  raw_data: "data/raw/travel_data.json"
  processed_data: "data/processed/embedded_docs.pkl"
  index_path: "data/processed/index.faiss"

# External API Settings
apis:
  yelp:
    base_url: "https://api.yelp.com/v3"
    max_results: 50
  google_maps:
    base_url: "https://maps.googleapis.com/maps/api"
    default_zoom: 13 